import AppKit

// MARK: - Help menu

@MainActor
final class HelpMenu: NSObject {

    /// Target for the link items; each carries its URL in `representedObject`.
    private static let linkTarget = HelpMenu()

    /// The top-level "Help" menu item (with its submenu). Assign the submenu to
    /// `NSApplication.helpMenu` so AppKit adds its search field.
    static func build() -> NSMenuItem {
        let helpMenuItem = NSMenuItem()
        let helpMenu = NSMenu(title: "Help")

        // No help book yet: showHelp: puts up AppKit's own "Help isn't
        // available for Edmund." alert.
        helpMenu.addItem(withTitle: "Edmund Help",
                         action: #selector(NSApplication.showHelp(_:)),
                         keyEquivalent: "?")
        helpMenu.addItem(withTitle: "Keyboard Shortcuts",
                         action: #selector(AppDelegate.showKeyBindings(_:)),
                         keyEquivalent: "")

        helpMenu.addItem(.separator())

        // Safari-style: a local HTML page, generated by build-app.sh from
        // LICENSES/. Absent under `swift run`, which bundles no resources.
        if let acknowledgments = Bundle.main.url(forResource: "Acknowledgments", withExtension: "html") {
            addLink("Acknowledgments", acknowledgments, to: helpMenu)
        }
        // ponytail: page not live yet; 404s until edmund.md ships an icon gallery.
        addLink("App Icons", "https://edmund.md/icons", to: helpMenu)
        addLink("Release Notes", "https://github.com/I7T5/Edmund/releases", to: helpMenu)
        addLink("Report a Bug\u{2026}",
                "https://github.com/I7T5/Edmund/issues/new?template=bug_report.md", to: helpMenu)
        addLink("Star on GitHub", "https://github.com/I7T5/Edmund", to: helpMenu)
        addLink("Website", "https://edmund.md", to: helpMenu)

        helpMenuItem.submenu = helpMenu
        return helpMenuItem
    }

    private static func addLink(_ title: String, _ url: String, to menu: NSMenu) {
        addLink(title, URL(string: url)!, to: menu)
    }

    private static func addLink(_ title: String, _ url: URL, to menu: NSMenu) {
        let item = menu.addItem(withTitle: title, action: #selector(openLink(_:)), keyEquivalent: "")
        item.target = linkTarget
        item.representedObject = url
    }

    @objc private func openLink(_ sender: NSMenuItem) {
        guard let url = sender.representedObject as? URL else { return }
        // A local .html goes to whatever owns the file type — often a code
        // editor. Hand it to the default web browser (the https handler).
        if url.isFileURL, let browser = NSWorkspace.shared.urlForApplication(toOpen: URL(string: "https:")!) {
            NSWorkspace.shared.open([url], withApplicationAt: browser, configuration: NSWorkspace.OpenConfiguration())
        } else {
            NSWorkspace.shared.open(url)
        }
    }
}
